/**
 * Bond Tokenization Service
 * Bond Tokenization Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@aad.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * JSON Schema for a user setting resource model
 */
 export interface UserSettingResourceModel {
  id: string;

  username: string;

  password: string;
}
